name: CI

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: frontendApp

jobs:
  build:
    runs-on: [ubuntu-latest]
    container:
      options: --user 1001
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: |
        npm run test
        env:
          CI: true
